#!/bin/bash

# postinst script for mx-updater

if command -v py3compile >/dev/null 2>&1; then
	py3compile -p mx-updater /usr/libexec/mx-updater  || true
fi
if command -v pypy3compile >/dev/null 2>&1; then
	pypy3compile -p mx-updater /usr/libexec/mx-updater || true
fi


case "$1" in
  configure)
	if [ ! -f /etc/apt/apt.conf.d/02periodic ]; then
		cp /usr/share/mx-updater/02periodic /etc/apt/apt.conf.d/02periodic
	fi
	if  [ ! -f /etc/apt/apt.conf.d/51unattended-upgrades-config ] && \
	    [ -f /usr/share/mx-updater/51unattended-upgrades-config ]; then
		  cp /usr/share/mx-updater/51unattended-upgrades-config \
		     /etc/apt/apt.conf.d/51unattended-upgrades-config 2>/dev/null || :
	fi

	if  [ -f /usr/share/mx-updater/51unattended-upgrades-default-origins ]; then
	    if  [ -f /etc/apt/apt.conf.d/51unattended-upgrades-default-origins ]; then
	       rm -f /etc/apt/apt.conf.d/51unattended-upgrades-default-origins || :
	    fi
	    cp /usr/share/mx-updater/51unattended-upgrades-default-origins \
	       /etc/apt/apt.conf.d/51unattended-upgrades-default-origins 2>/dev/null || :
	fi

	if  [ -f /usr/share/mx-updater/51unattended-upgrades-blacklist ]; then
	    if  [ -f /etc/apt/apt.conf.d/51unattended-upgrades-blacklist ]; then
	       rm -f /etc/apt/apt.conf.d/51unattended-upgrades-blacklist || :
	    fi
	    cp /usr/share/mx-updater/51unattended-upgrades-blacklist \
	       /etc/apt/apt.conf.d/51unattended-upgrades-blacklist 2>/dev/null || :
	fi

        if [ -d /run/systemd/system ]; then
            systemctl --system daemon-reload >/dev/null || :
        fi

	gtk-update-icon-cache -f -t /usr/share/icons/hicolor/ 2>/dev/null || true

	chmod 0440 /etc/sudoers.d/mx-updater-reload 2>/dev/null || true

	;;
esac
exit 0
